/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_27082026;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {

        initComponents();
        
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        DefaultListModel modeloLista = new DefaultListModel();
        
        DefaultTableModel modeloTabla = new DefaultTableModel();
        
//        

        jcb_ver.setModel(modelo);
        jcb_modificar.setModel(modelo);
        jcb_eliminar.setModel(modelo);
        
        
        jl_listaPersonas.setModel(modeloLista);
        
        
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellido");

        jt_personas.setModel(modeloTabla);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpm_menuOpciones = new javax.swing.JPopupMenu();
        jmi_limpiar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmi_mostrar = new javax.swing.JMenuItem();
        jpm_opcionesLista = new javax.swing.JPopupMenu();
        jmi_editar = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        jd_settings = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txt_nombreDialog = new javax.swing.JTextField();
        tabsPrincipales = new javax.swing.JTabbedPane();
        jp_agregar = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jp_ver = new javax.swing.JPanel();
        jcb_ver = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_mostrarNombre = new javax.swing.JTextField();
        txt_mostrarApellido = new javax.swing.JTextField();
        jp_modificar = new javax.swing.JPanel();
        jcb_modificar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_modificarNombre = new javax.swing.JTextField();
        txt_modificarApellido = new javax.swing.JTextField();
        btn_modificar = new javax.swing.JButton();
        jp_eliminar = new javax.swing.JPanel();
        jcb_eliminar = new javax.swing.JComboBox<>();
        btn_eliminar = new javax.swing.JButton();
        jp_ejemplo = new javax.swing.JPanel();
        jcbLista = new javax.swing.JComboBox<>();
        lblTextoSeleccionado = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_listaPersonas = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_personas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lbl_filaTabla = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_columnaTabla = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        lbl_label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbl_valorTabla = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jmi_limpiar.setText("Limpiar");
        jpm_menuOpciones.add(jmi_limpiar);
        jpm_menuOpciones.add(jSeparator1);

        jmi_mostrar.setText("Mostrar");
        jmi_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_mostrarActionPerformed(evt);
            }
        });
        jpm_menuOpciones.add(jmi_mostrar);

        jmi_editar.setText("Editar");
        jmi_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_editarActionPerformed(evt);
            }
        });
        jpm_opcionesLista.add(jmi_editar);

        jmi_eliminar.setText("Eliminar");
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        jpm_opcionesLista.add(jmi_eliminar);

        jLabel8.setText("Datos");

        jButton2.setText("Modificar en Padre");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        txt_nombreDialog.setText("jTextField2");

        javax.swing.GroupLayout jd_settingsLayout = new javax.swing.GroupLayout(jd_settings.getContentPane());
        jd_settings.getContentPane().setLayout(jd_settingsLayout);
        jd_settingsLayout.setHorizontalGroup(
            jd_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_settingsLayout.createSequentialGroup()
                .addGroup(jd_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_settingsLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel8))
                    .addGroup(jd_settingsLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(jd_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombreDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jd_settingsLayout.setVerticalGroup(
            jd_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_settingsLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel8)
                .addGap(39, 39, 39)
                .addComponent(txt_nombreDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton2)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_agregarMouseClicked(evt);
            }
        });

        lblNombre.setText("Nombre");

        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_agregarLayout = new javax.swing.GroupLayout(jp_agregar);
        jp_agregar.setLayout(jp_agregarLayout);
        jp_agregarLayout.setHorizontalGroup(
            jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarLayout.createSequentialGroup()
                .addGroup(jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_agregarLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblNombre)
                        .addGap(41, 41, 41)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_agregarLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(btnAgregar)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jp_agregarLayout.setVerticalGroup(
            jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(50, 50, 50))
        );

        tabsPrincipales.addTab("Agregar", jp_agregar);

        jcb_ver.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_verActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        javax.swing.GroupLayout jp_verLayout = new javax.swing.GroupLayout(jp_ver);
        jp_ver.setLayout(jp_verLayout);
        jp_verLayout.setHorizontalGroup(
            jp_verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_verLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jp_verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_verLayout.createSequentialGroup()
                        .addGroup(jp_verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(jp_verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_mostrarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                            .addComponent(txt_mostrarApellido))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jp_verLayout.setVerticalGroup(
            jp_verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_verLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jcb_ver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jp_verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_mostrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jp_verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_mostrarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        tabsPrincipales.addTab("Ver", jp_ver);

        jcb_modificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_modificarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        btn_modificar.setText("modificar");
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_modificarLayout = new javax.swing.GroupLayout(jp_modificar);
        jp_modificar.setLayout(jp_modificarLayout);
        jp_modificarLayout.setHorizontalGroup(
            jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modificarLayout.createSequentialGroup()
                .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_modificarLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp_modificarLayout.createSequentialGroup()
                                .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(57, 57, 57)
                                .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_modificarNombre)
                                    .addComponent(txt_modificarApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)))))
                    .addGroup(jp_modificarLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(btn_modificar)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jp_modificarLayout.setVerticalGroup(
            jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modificarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jcb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_modificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_modificarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btn_modificar)
                .addContainerGap())
        );

        tabsPrincipales.addTab("Modificar", jp_modificar);

        jcb_eliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_eliminarLayout = new javax.swing.GroupLayout(jp_eliminar);
        jp_eliminar.setLayout(jp_eliminarLayout);
        jp_eliminarLayout.setHorizontalGroup(
            jp_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_eliminarLayout.createSequentialGroup()
                .addGroup(jp_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_eliminarLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jcb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_eliminarLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(btn_eliminar)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jp_eliminarLayout.setVerticalGroup(
            jp_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_eliminarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jcb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btn_eliminar)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        tabsPrincipales.addTab("Eliminar", jp_eliminar);

        jcbLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "iNG.Sistemas", "ing", "industrial", "derecho" }));
        jcbLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbListaActionPerformed(evt);
            }
        });

        lblTextoSeleccionado.setText("jLabel1");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jp_ejemploLayout = new javax.swing.GroupLayout(jp_ejemplo);
        jp_ejemplo.setLayout(jp_ejemploLayout);
        jp_ejemploLayout.setHorizontalGroup(
            jp_ejemploLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ejemploLayout.createSequentialGroup()
                .addGroup(jp_ejemploLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_ejemploLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jcbLista, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_ejemploLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(lblTextoSeleccionado)
                        .addGap(87, 87, 87)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        jp_ejemploLayout.setVerticalGroup(
            jp_ejemploLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ejemploLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jcbLista, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jp_ejemploLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoSeleccionado)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        tabsPrincipales.addTab("EjemploCopmboBox", jp_ejemplo);

        jl_listaPersonas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jl_listaPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_listaPersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_listaPersonas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        tabsPrincipales.addTab("Listas", jPanel1);

        jt_personas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_personas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_personasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_personas);

        jLabel5.setText("Fila seleccionada");

        lbl_filaTabla.setText("jLabel6");

        jLabel7.setText("Columna selecionada");

        lbl_columnaTabla.setText("jLabel8");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5)
                        .addGap(44, 44, 44)
                        .addComponent(lbl_filaTabla)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel7)
                        .addGap(47, 47, 47)
                        .addComponent(lbl_columnaTabla)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbl_filaTabla)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lbl_columnaTabla))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabsPrincipales.addTab("Tablas", jPanel2);

        jButton3.setText("color");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        lbl_label.setText("jLabel9");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(60, 60, 60))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(lbl_label)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(lbl_label)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        tabsPrincipales.addTab("tab8", jPanel3);

        jButton1.setText("Eliminar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel6.setText("Valor seleccionado");

        lbl_valorTabla.setText("jLabel7");

        jMenu1.setText("Guardar");

        jMenu2.setText("Guardar como");

        jMenuItem2.setText("PDF File");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Word");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("texto");
        jMenu2.add(jMenuItem4);

        jMenu1.add(jMenu2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, 0));
        jMenuItem1.setText("Guardar contenido actual");
        jMenuItem1.setToolTipText("");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Limpiar");

        jMenuItem5.setText("Limpiar pantalla");
        jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem5MouseClicked(evt);
            }
        });
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(tabsPrincipales, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButton1)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6)
                        .addGap(44, 44, 44)
                        .addComponent(lbl_valorTabla)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tabsPrincipales, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel6)
                    .addComponent(lbl_valorTabla))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbListaActionPerformed
        int pos = jcbLista.getSelectedIndex();
        Object elemento = jcbLista.getSelectedItem();

        System.out.println("indice " + pos);
        System.out.println("Valor " + elemento);

        lblTextoSeleccionado.setText(elemento.toString());
    }//GEN-LAST:event_jcbListaActionPerformed

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        String nombre = txt_nombre.getText();
        Persona nuevaPersona = new Persona(nombre, nombre);

        //modelo del combobox.
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) jcb_ver.getModel();
//               if(jcb_agregar.getModel() instanceof DefaultComboBoxModel){
//                   System.out.println("es un DefaultComboBoxModel");
//               }
//       
        System.out.println("MODELO " + jcb_ver.getModel().getClass());;
        modelo.addElement(nuevaPersona);
        
        
        // agregara a la lista 
        
        DefaultListModel modeloLista = (DefaultListModel)jl_listaPersonas.getModel();
        
        
        modeloLista.addElement(nuevaPersona);
        
        
        
        /// Agregar el elemento a la tabla 
        
        DefaultTableModel modeloTabla = (DefaultTableModel)jt_personas.getModel();
        
        Object [] datos = {nuevaPersona, nuevaPersona.getApellido()};
        
        modeloTabla.addRow(datos);
        
        JOptionPane.showMessageDialog(this, "Persona creada con exito");

    }//GEN-LAST:event_btnAgregarMouseClicked

    private void jcb_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_verActionPerformed
        Object elementoSeleccionado = jcb_ver.getSelectedItem();
        if (elementoSeleccionado instanceof Persona) {
            Persona p = (Persona) elementoSeleccionado;
            txt_mostrarNombre.setText(p.getNombre());
            txt_mostrarApellido.setText(p.getApellido());

        }
    }//GEN-LAST:event_jcb_verActionPerformed

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked

        String nuevoNombre = txt_modificarNombre.getText();
        String nuevoApellido = txt_modificarApellido.getText();
        Object persona = jcb_modificar.getSelectedItem();
        if (persona instanceof Persona) {
            Persona personaSeleccionada = (Persona) persona;
            personaSeleccionada.setNombre(nuevoNombre);
            personaSeleccionada.setApellido(nuevoApellido);
            JOptionPane.showMessageDialog(this, "Datos actualizados");
        }
    }//GEN-LAST:event_btn_modificarMouseClicked

    private void jcb_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_modificarActionPerformed
        Object persona = jcb_modificar.getSelectedItem();
        if (persona instanceof Persona) {
            Persona personaSeleccionada = (Persona) persona;
            txt_modificarNombre.setText(personaSeleccionada.getNombre());
            txt_modificarApellido.setText(personaSeleccionada.getApellido());
        }
    }//GEN-LAST:event_jcb_modificarActionPerformed

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        int pos = jcb_eliminar.getSelectedIndex();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) jcb_eliminar.getModel();
        modelo.removeElementAt(pos);
        JOptionPane.showMessageDialog(this, "Datos actualizados");
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void jMenuItem5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MouseClicked

    }//GEN-LAST:event_jMenuItem5MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        txt_nombre.setText("");
        txt_mostrarNombre.setText("");
        txt_mostrarApellido.setText("");
        txt_modificarNombre.setText("");
        txt_modificarApellido.setText("");
        JOptionPane.showMessageDialog(this, "Pantalla limpia :)");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jp_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_agregarMouseClicked
        int boton = evt.getButton();
        if (boton == 1) {
            System.out.println("Seleccionar");
        }  else if(boton==3){
          //pop up menu 
          int x = evt.getX();
          int y= evt.getY();
          jpm_menuOpciones.show(jp_agregar,x ,y );
          
          
        }
//        
    }//GEN-LAST:event_jp_agregarMouseClicked

    private void jl_listaPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_listaPersonasMouseClicked
        System.out.println("click!");
        if(evt.getButton()==3){
            System.out.println("derecho");
            jpm_opcionesLista.show(jl_listaPersonas, evt.getX(), evt.getY());
        }else{
            System.out.println(evt.getButton());
        }
        
    }//GEN-LAST:event_jl_listaPersonasMouseClicked

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed
        int index = jl_listaPersonas.getSelectedIndex();
        if(index!=-1){
            DefaultListModel modelo = (DefaultListModel)jl_listaPersonas.getModel();
            modelo.remove(index);
               JOptionPane.showMessageDialog(this, "Elemento eliminado! ");
       }else{
          JOptionPane.showMessageDialog(this, "No hay nignun elemento seleccionado ");
      }
    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jmi_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_editarActionPerformed
        int index = jl_listaPersonas.getSelectedIndex();
      if(index!=-1){
            DefaultListModel modelo = (DefaultListModel)jl_listaPersonas.getModel();
            Object elementoSleccionado = modelo.getElementAt(index);
            if(elementoSleccionado instanceof Persona){
                Persona personaSeleccionada = (Persona)elementoSleccionado;
                String nuevoNombre = JOptionPane.showInputDialog("Ingrese el nombre:");
                personaSeleccionada.setNombre(nuevoNombre);
                 JOptionPane.showMessageDialog(this, "Datos actualizados");
                
            }
        }else{
          JOptionPane.showMessageDialog(this, "No hay nignun elemento seleccionado ");
      }
    }//GEN-LAST:event_jmi_editarActionPerformed

    private void jt_personasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_personasMouseClicked
     int columna= jt_personas.getSelectedColumn();
     int fila = jt_personas.getSelectedRow();
     
     DefaultTableModel modeloTabla = (DefaultTableModel)jt_personas.getModel();
     
     Object valor = modeloTabla.getValueAt(fila, columna);
     lbl_filaTabla.setText(fila+"");
     lbl_columnaTabla.setText(columna+"");
     lbl_valorTabla.setText(valor.toString());
    
      
     // taano de las filas = matriz.length  == modeloTabla.getRowCount()
     // tamano de las columnas matriz[i].length ==  modeloTabla.getColumnCount()
     // valor en una pos i, j matriz[i][j] == modeloTabla.getValueAt(i, j);
     
    }//GEN-LAST:event_jt_personasMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
         int columna= jt_personas.getSelectedColumn();
     int fila = jt_personas.getSelectedRow();
        System.out.println("Fila seleccionada:"+fila);
     DefaultTableModel modeloTabla = (DefaultTableModel)jt_personas.getModel();
     if(fila!=-1){
     modeloTabla.removeRow(fila);
     JOptionPane.showMessageDialog(this, "Fila eliminada! ");
     
     }else{
          JOptionPane.showMessageDialog(this, "No hay nignun elemento seleccionado ");
      }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jmi_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_mostrarActionPerformed
        jd_settings.pack();
        jd_settings.setVisible(true);
        
    }//GEN-LAST:event_jmi_mostrarActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        txt_nombre.setText(txt_nombreDialog.getText());
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        
        
        Color seleccionado = JColorChooser.showDialog(this, "Seleccione un colorcito",Color.CYAN);
        lbl_label.setOpaque(true);
        lbl_label.setBackground(seleccionado);
        
        
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });        
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jcbLista;
    private javax.swing.JComboBox<String> jcb_eliminar;
    private javax.swing.JComboBox<String> jcb_modificar;
    private javax.swing.JComboBox<String> jcb_ver;
    private javax.swing.JDialog jd_settings;
    private javax.swing.JList<String> jl_listaPersonas;
    private javax.swing.JMenuItem jmi_editar;
    private javax.swing.JMenuItem jmi_eliminar;
    private javax.swing.JMenuItem jmi_limpiar;
    private javax.swing.JMenuItem jmi_mostrar;
    private javax.swing.JPanel jp_agregar;
    private javax.swing.JPanel jp_ejemplo;
    private javax.swing.JPanel jp_eliminar;
    private javax.swing.JPanel jp_modificar;
    private javax.swing.JPanel jp_ver;
    private javax.swing.JPopupMenu jpm_menuOpciones;
    private javax.swing.JPopupMenu jpm_opcionesLista;
    private javax.swing.JTable jt_personas;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTextoSeleccionado;
    private javax.swing.JLabel lbl_columnaTabla;
    private javax.swing.JLabel lbl_filaTabla;
    private javax.swing.JLabel lbl_label;
    private javax.swing.JLabel lbl_valorTabla;
    private javax.swing.JTabbedPane tabsPrincipales;
    private javax.swing.JTextField txt_modificarApellido;
    private javax.swing.JTextField txt_modificarNombre;
    private javax.swing.JTextField txt_mostrarApellido;
    private javax.swing.JTextField txt_mostrarNombre;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombreDialog;
    // End of variables declaration//GEN-END:variables
}
