/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_2408026;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        // Previo al render 
        initComponents();// renderizado 
        // Render completo 
        pantallaMail(false);
         

   
        
    }
    
    
    void pantallaMail(boolean mostrar){
//        txtNombre.setVisible(mostrar);
//        txtMensaje.setVisible(mostrar);
//        btnPrinicpal.setVisible(mostrar);
//        lblCorreo.setVisible(mostrar);
//        lblMensaje.setVisible(mostrar);
//        scroll.setVisible(mostrar);
          jpCorreo.setVisible(mostrar);
    }
    
    void historialMails(boolean mostrar){
//        lblHistorial.setVisible(mostrar);
//        txtHistorial.setVisible(mostrar);
//        btnRedactar.setVisible(mostrar);
//        scrollHistorial.setVisible(mostrar);
          jpHistorial.setVisible(mostrar);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpHistorial = new javax.swing.JPanel();
        lblHistorial = new javax.swing.JLabel();
        scrollHistorial = new javax.swing.JScrollPane();
        txtHistorial = new javax.swing.JTextArea();
        btnRedactar = new javax.swing.JButton();
        jpCorreo = new javax.swing.JPanel();
        lblCorreo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblMensaje = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        txtMensaje = new javax.swing.JTextArea();
        btnPrinicpal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jpHistorial.setBackground(new java.awt.Color(204, 255, 204));

        lblHistorial.setText("Historial");

        txtHistorial.setColumns(20);
        txtHistorial.setRows(5);
        txtHistorial.setEnabled(false);
        scrollHistorial.setViewportView(txtHistorial);

        btnRedactar.setText("Redactar Nuevo!");
        btnRedactar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRedactarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpHistorialLayout = new javax.swing.GroupLayout(jpHistorial);
        jpHistorial.setLayout(jpHistorialLayout);
        jpHistorialLayout.setHorizontalGroup(
            jpHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHistorialLayout.createSequentialGroup()
                .addGroup(jpHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpHistorialLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(lblHistorial))
                    .addGroup(jpHistorialLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(scrollHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRedactar)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jpHistorialLayout.setVerticalGroup(
            jpHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHistorialLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblHistorial)
                .addGroup(jpHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpHistorialLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpHistorialLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnRedactar)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(jpHistorial);

        jpCorreo.setBackground(new java.awt.Color(255, 204, 204));

        lblCorreo.setText("Correo Destinatario");

        txtNombre.setBackground(new java.awt.Color(204, 204, 255));
        txtNombre.setForeground(new java.awt.Color(51, 51, 255));

        lblMensaje.setText("Mensaje");

        txtMensaje.setColumns(20);
        txtMensaje.setRows(5);
        scroll.setViewportView(txtMensaje);

        btnPrinicpal.setBackground(new java.awt.Color(204, 204, 255));
        btnPrinicpal.setFont(new java.awt.Font("Lao Sangam MN", 3, 36)); // NOI18N
        btnPrinicpal.setText("Enviar");
        btnPrinicpal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrinicpalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpCorreoLayout = new javax.swing.GroupLayout(jpCorreo);
        jpCorreo.setLayout(jpCorreoLayout);
        jpCorreoLayout.setHorizontalGroup(
            jpCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCorreoLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(btnPrinicpal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpCorreoLayout.createSequentialGroup()
                .addGroup(jpCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCorreoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblCorreo))
                    .addGroup(jpCorreoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblMensaje)))
                .addGap(32, 32, 32)
                .addGroup(jpCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCorreoLayout.createSequentialGroup()
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpCorreoLayout.createSequentialGroup()
                        .addComponent(txtNombre)
                        .addGap(29, 29, 29))))
        );
        jpCorreoLayout.setVerticalGroup(
            jpCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCorreoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jpCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCorreoLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblMensaje))
                    .addGroup(jpCorreoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addComponent(btnPrinicpal)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        getContentPane().add(jpCorreo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrinicpalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrinicpalMouseClicked
        String destinatario = txtNombre.getText();
        String mensaje = txtMensaje.getText();
        
        Correo nuevoCorreo = new Correo(destinatario,mensaje);
        System.out.println(nuevoCorreo);
        JOptionPane.showMessageDialog(this, "Correo enviado exitosamente");
        
        txtNombre.setText(null);
        txtMensaje.setText(null);
        
        historialMails(true);
        pantallaMail(false);
        correosEnviados.add(nuevoCorreo);
        cargarHistorialCorreo();
    }//GEN-LAST:event_btnPrinicpalMouseClicked

    void cargarHistorialCorreo(){
         txtHistorial.append(null);
        for (Correo correosEnviado : correosEnviados) {
             txtHistorial.append("_____________________________\n");
             txtHistorial.append(correosEnviado.toString());
             txtHistorial.append("\n_____________________________\n");
        }
        
    }
    private void btnRedactarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRedactarMouseClicked
        //mostrar elementos de redactar correo 
                pantallaMail(true);
                historialMails(false);
                
    }//GEN-LAST:event_btnRedactarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrinicpal;
    private javax.swing.JButton btnRedactar;
    private javax.swing.JPanel jpCorreo;
    private javax.swing.JPanel jpHistorial;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblHistorial;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JScrollPane scrollHistorial;
    private javax.swing.JTextArea txtHistorial;
    private javax.swing.JTextArea txtMensaje;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Correo> correosEnviados = new ArrayList<>();
}
